---
- name: Ensure supervisor is installed
  apt: name=supervisor state=present

- name: Ensure supervisor is started
  service: name=supervisor state=started enabled=yes

- name: Copy app script
  template:
      src=supervisor.conf.j2
      dest=/etc/supervisor/conf.d/{{ app_name }}.conf
      owner=root
      group=root
      mode=0644
  notify:
      - Read supervisor conf
      - Ensure app in supervisor

