---
- hosts: all
  gather_facts: no
  become: True
  tasks:
      - name: Install python 2.x
        raw: apt-get update -qq && apt-get install -qq python

- hosts: all
  user: ubuntu
  become: True
  vars_files:
      - ../vagrant.yml
  roles:
      - provision
      - app
      - postgresql
      - migrations
      - supervisor
      - nginx

